[psi]
avg10_warn = 0.50
avg10_crit = 1.00

[mem]
available_warn_kib = 524288     # 512 MiB
available_crit_kib = 262144     # 256 MiB

[ui.palette]
green = "shield-green"
yellow = "shield-yellow"
orange = "shield-orange"
red = "shield-red"
black = "shield-black"

[sample]
interval_ms = 2000
