[psi]
avg10_warn = 0.50
avg10_crit = 1.00

[mem]
available_warn_kib = 524288     # 512 MiB
available_crit_kib = 262144     # 256 MiB

[ui.palette]
green = "res/icons/shield-green.svg"
yellow = "res/icons/shield-yellow.svg"
orange = "res/icons/shield-orange.svg"
red = "res/icons/shield-red.svg"

[sample]
interval_ms = 2000
